apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-serverless-functions
  namespace: kube-serverless
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: functions.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-serverless-api
            port:
              number: 80
